build(svelte5): replace jsdom by happy-dom because of CommonJs issues
This fixed the following error when running tests :
```
Error: require() of ES Module /Users/marco/env/iroco/src/iroco-ui/node_modules/@asamuzakjp/css-color/dist/esm/css-color.min.js from /Users/marco/env/iroco/src/iroco-ui/node_modules/cssstyle/lib/parsers.js not supported.
Instead change the require of css-color.min.js in /Users/marco/env/iroco/src/iroco-ui/node_modules/cssstyle/lib/parsers.js to a dynamic import() which is available in all CommonJS modules.
 ```